name: Semester Tract
description: File a bug report
title: "[Semester] "
labels: ["semetract", "semester"]
assignees:
  - habatchii
body:
  - type: markdown
    attributes:
      value: |
        The followig report is used to build your team's docket. Please complete it using your team's electroplate!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Active E-Mail on File
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Semester Tract Type
      description: Proposition/Ammend/Mandate ?
      placeholder: Type of issue P, A or M.
      value: "Bounties Applying for:"
    validations:
      required: true
  - type: dropdown
    id: semetract
    attributes:
      label: Semester Tract Data
      multiple: true
      description: What tracts are you installing?
      options:
        - SemeTract_Elections
        - SemeTract_Emergency & Disaster
        - SemeTract_Engineering
        - SemeTract_Ethics
        - SemeTract_Ethinic Bylaws; Urbanization
        - SemeTract_Family Counsel (Homestead Management) 
        - SemeTract_Farming 
        - SemeTract_Farming; Agriculture 
        - SemeTract_Finance; Business 
        - SemeTract_Finance; Personal 
        - SemeTract_Financial Assistance 
        - SemeTract_Financial Assistance; Emergency 
        - SemeTract_Health Services; SHI/IHT 
        - SemeTract_Hydrolics, Electric & Lumanance(HEL) 
        - SemeTract_Industrial; TICS 
        - SemeTract_Inter-City Operations 
        - SemeTract_Inter-State Operations 
        - SemeTract_Inter-Government Operations 
        - SemeTract_Juvenile Services;(TBA) 
        - SemeTract_Labor (see TLC) 
        - SemeTract_Law; Public Defense 
        - SemeTract_Law; Enforcement 
        - SemeTract_Meterological & Telicalogical Systems 
        - SemeTract_Model Recognition; Quality Utilization 
        - SemeTract_Planned Parenting 
        - SemeTract_Population Control (TERO) 
        - SemeTract_Press & Media 
        - SemeTract_Press & Media; Pro Rata Coverage 
        - SemeTract_Probate & Concessions; Forfietures 
        - SemeTract_Technology & Research 
        - SemeTract_Trade, Labor & Commerce (TLC) 
        - SemeTract_Traffic & Road Safety 
        - SemeTract_Transportation 
        - SemeTract_Transportation (Airline Regulation) 
        - SemeTract_Undercare Provision 
        
    validations:
      required: true
  - type: dropdown
    id: Active_Platform
    attributes:
      label: What is your team's Active Platform?
      options:
        - Administrative 
        - Arbitrative 
        - Paralegal 
        - Enforcement 
        - Research 
        - Commissions 
        - Accountability 
        - Annexations
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this semester tract, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
